apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-rolling-update
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
      - name: hello
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
