apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello 
        version: v2
    spec:
      containers:
      - name: hello
        image: jocatalin/kubernetes-bootcamp:v2
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
